# Generated by Django 2.1.1 on 2018-09-28 06:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20180926_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='travel_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='旅遊日期'),
            preserve_default=False,
        ),
    ]
